# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSerHelper-Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'iOSerHelper', :path => '../iOSerHelper'
  # Pods for iOSerHelper-Client

  target 'iOSerHelper-ClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSerHelper-ClientUITests' do
    # Pods for testing
  end

end
